spring:
  profiles:
    active: local

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
    resource:
      token-info-uri: ${custom.auth.server}/oauth/check_token
      user-info-uri: ${custom.auth.server}/me



logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: TRACE


---
spring:
  profiles: local

custom:
  auth:
    server: http://localhost:8081

---
spring:
  profiles: docker

custom:
  auth:
    server: http://AuthHost:8081