FROM openjdk:8-jdk-slim as builder

ENV APP_HOME=/app/java
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY build.gradle .
COPY settings.gradle .
COPY gradlew .
COPY gradlew.bat .
COPY gradle .
RUN ./gradlew build -x test || return 0 
COPY . .
RUN ./gradlew build -x test

FROM openjdk:8-jre-slim

RUN mkdir -p /app/java
WORKDIR /app/java

COPY --from=builder /app/java/build/unpack/lib BOOT-INF/lib
COPY --from=builder /app/java/build/unpack/app .

CMD ["java", "-Duser.timezone=Asia/Seoul", "-Dfile.encoding=utf-8", "-Dspring.profiles.active=docker", "org.springframework.boot.loader.JarLauncher"]